---
aiohttp_settings:
  client_max_size: 20971520
databases:
  - db:
      storage: postgresql
      transaction_strategy: dbresolve_readcommitted
      dsn: postgresql://guillotina:guillotina@postgres:5432/guillotina
      read_only: false
      pool_size: 100
store_json: true
allow_register: true
jwk:
  k: hGplrewNAVxULSApZavdXuxdiR_2Ner73oc-2Z7TVVY
  kty: oct
cache:
  driver: guillotina.contrib.redis
  updates_channel: guillotina
applications:
  - guillotina_cms
  - guillotina.contrib.cache
  - guillotina.contrib.catalog.pg
  - guillotina.contrib.dbusers
  - guillotina.contrib.mailer
  - guillotina.contrib.redis
  - guillotina.contrib.pubsub
  - guillotina.contrib.email_validation
  - guillotina.contrib.templates
  - guillotina.contrib.redis_session
  - guillotina_authentication
host: 0.0.0.0
address: 8081
static:
  - favicon.png: static/favicon.png
  - assets: guillotina:static/assets
root_user:
  password: root
mailer:
  utility:
    guillotina.contrib.mailer.utility.PrintingMailerUtility
auth_extractors:
  - guillotina.auth.extractors.CookiePolicy
  - guillotina.auth.extractors.BearerAuthPolicy
  - guillotina.auth.extractors.BasicAuthPolicy
  - guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
  - guillotina.auth.validators.SaltedHashPasswordValidator
  - guillotina.auth.validators.JWTValidator
auth_user_identifiers:
  - guillotina.contrib.dbusers.users.DBUserIdentifier
redis:
  host: redis
  port: 6379
jwt:
  secret: secret
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner
cors:
  allow_origin:
    - '*'
  allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - OPTIONS
    - PUT
  allow_headers:
    - '*'
  expose_headers:
    - '*'
  allow_credentials: true
  max_age: 3660
global_disallowed_types:
  - User
  - UserManager
  - Group
  - GroupManager
  - Item
  - Container
  - Folder
contents:
  player:
    title: Player
    inherited_interface: guillotina.interfaces.IItem
    inherited_class: guillotina.content.Item
    add_permission: guillotina.AddContent
    properties:
      rank:
        type: guillotina.schema.Int
        title: Rank
  team:
    title: Team
    inherited_interface: guillotina.interfaces.IFolder
    inherited_class: guillotina.content.Folder
    add_permission: guillotina.AddContent
    allowed_types:
      - player
    properties:
      contests:
        type: guillotina.schema.JSONField
        title: Contests
default_tiles:
  Document:
    tiles:
      tile1:
        '@type': title
      tile2:
        '@type': description
      tile3:
        text: null
        '@type': text
    tiles_layout:
      - tile1
      - tile2
      - tile3
  Container:
    tiles:
      tile1:
        '@type': title
      tile2:
        '@type': description
      tile3:
        text: null
        '@type': text
    tiles_layout:
      items:
        - tile1
        - tile2
        - tile3
myoptions:
  - - guillotina
    - Also Love Guillotina
  - - volto
    - Also Love Volto
workflows:
  basic:
    initial_state: private
    states:
      private:
        actions:
          publish:
            title: Publish
            to: public
            check_permission: guillotina.ReviewContent
        set_permission:
          roleperm:
            - setting: Deny
              role: guillotina.Anonymous
              permission: guillotina.ViewContent
            - setting: Deny
              role: guillotina.Anonymous
              permission: guillotina.AccessContent
      public:
        actions:
          retire:
            title: Retire
            to: private
            check_permission: guillotina.ReviewContent
        set_permission:
          roleperm:
            - setting: AllowSingle
              role: guillotina.Anonymous
              permission: guillotina.ViewContent
            - setting: AllowSingle
              role: guillotina.Anonymous
              permission: guillotina.AccessContent
workflows_content:
  guillotina.interfaces.IResource: basic
  guillotina_cms.content.document.IDocument: guillotina_simple_publication
allow_discussion_types:
  - Document
