name: Deploy
env:
    CI: true
on:
    push:
        branches:
            - master
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup Node
              uses: actions/setup-node@v1
            - run: npm install
            - name: Tag
              run: ./tag-version.sh
            - run: npm run build
            - name: Publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./dist/grange/package.json
